# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ukpython', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('venue', models.CharField(max_length=255, null=True)),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ukpython.UserGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
