# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ukpython', '0004_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='newsletter_month',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
