# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ukpython', '0005_newsitem_newsletter_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('content_format', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'ordering': ['name']},
        ),
    ]
