# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-01 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ukpython', '0006_auto_20170223_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='newsletter_only',
            field=models.BooleanField(default=False),
        ),
    ]
