# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-31 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ukpython', '0008_sponsor_sponsorednewsitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('content_format', models.CharField(max_length=255)),
                ('newsletter_month', models.CharField(max_length=7, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
